apiVersion: v1
kind: Service
metadata:
  name: factorizator
  namespace: factorizator
spec:
  type: NodePort
  selector:
    app: factorizator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31401  # FIXED port
